name: Deploy to EC2

on:
  workflow_dispatch:
    inputs:
      llm:
        description: 'LLM Model to deploy'
        required: true
      user:
        description: 'Login User'
        required: true
      host:
        description: 'Login Host'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      env:
        LLM_NAME: ${{ github.event.inputs.llm }}
        REMOTE_USER: ${{ github.event.inputs.user }}
        REMOTE_HOST: ${{ github.event.inputs.host }}
        HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
      run: |
        bash deploy.sh